var indices = [
    "android",
    "angular",
    "ajax",
    "apache",
    "apache-tomcat",
    "bootstrap",
    "css",
    "docker !!!",
    "eclypse",
    "fullcalendarjs !!!",
    "git", 
    "gitlab",
    "gitlab runner",
    "graddle",
    "hibernate",
    "html5",
    "intellij",
    "java",             
    "javascript",
    "jdbc",
    "jpa",
    "jsp",
    "junit",
    "maven",
    "micro services",
    "mysql",
    "node",
    "npm",
    "primeeng",
    "rest",
    "room",
    "sdk facebook !!!",
    "spring",
    "spring mvc",
    "springboot",
    "sql",
    "sqlite",
    "thymleaf",
    "tomcat",
    "visual studio code",
    "volley",
    "web services"
]
